Update README.mkd
mattn/emmet-vim pull request #523
Opened 2021-09-28 19:04 UTC by snxx-lppxx

2021-09-29 15:45 UTC, mattn requested changes

2021-09-29 15:45 UTC, mattn commented on README.mkd
> +</div>
Thanks. Please remove this div tag. I don't want html tags in markdown. I'll merge this PR.

2021-09-30 14:28 UTC, snxx-lppxx commented
Hi @mattn! Review this.

2021-09-30 14:47 UTC, merged

2021-09-30 14:48 UTC, mattn commented
Thank you